### ISSUE TITLE
cp: cannot stat './daemons/jackett': No such file or directory

### ISSUE THREAD

**Issue by Shadotak** [norbikaa/raspberry-sonarr-jackett#1]
The directions provided will give this error "cp: cannot stat './daemons/jackett': No such file or directory" when you get to these parts:

**Run Sonarr at startup**
If you would like to run Sonarr at startup, put sonarr daemon to /etc/init.d and set daemon to run automatically (You need to change TO_YOUR_USERNAME to username who will run the daemon):

```
sudo cp ./daemons/nzbdrone /etc/init.d/nzbdrone &&
sudo sed -i -e "s#YOUR_USERNAME#TO_YOUR_USERNAME#g" /etc/init.d/nzbdrone &&
sudo chmod a+x /etc/init.d/nzbdrone &&
sudo update-rc.d nzbdrone defaults
```

and then here

Then extract and move files to destination folder, change owner on destination folder to the actual user:
```
tar -xvf Jackett* &&
sudo mkdir /opt/jackett &&
sudo mv Jackett/* /opt/jackett &&
rm -rf Jackett* &&
sudo chown -R YOUR_USERNAME:YOUR_USERNAME /opt/jackett
```

and here

```
sudo cp ./daemons/jackett /etc/init.d/jackett &&
sudo sed -i -e "s#YOUR_USERNAME#TO_YOUR_USERNAME#g" /etc/init.d/jackett &&
sudo chmod a+x /etc/init.d/jackett &&
sudo update-rc.d jackett defaults
```

Did something change? Was I supposed to create a directory or file?

**Comment by ata-o** [comment]
this guide is useless. use the official installation guide: https://github.com/Jackett/Jackett

**Comment by Shadotak** [comment]
> this guide is useless. use the official installation guide: https://github.com/Jackett/Jackett

Dude, thank you so much.  I kept searching for raspberry pi related guides and that official github never came up.

**Comment by nfjodor** [comment]
Sorry for the late response. As @onuratasaritas mentioned, this repository is outdated, sorry for the inconvenience.
